version: '2.2.{build}'
image: Visual Studio 2017
configuration: Release
branches:
  only:
  - master
skip_commits:
  files:
    - README.md
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack /p:PackageVersion=%APPVEYOR_BUILD_VERSION% ./src/NCalc/NCalc.csproj
clone_depth: 1
test_script:
  - cmd: dotnet restore --verbosity m
  - cmd: dotnet test ./test/NCalc.Tests/NCalc.Tests.csproj
artifacts:
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: 3SWQ4emBt+OyCzfp6edbmm6JRHv5JVn+A1yVmXmPFUuvVQmpGTWVAGmnvsaS4Hgj
  skip_symbols: true
  artifact: /.*\.nupkg/
